FROM eclipsebasyx/aas-registry:1.5.0

RUN apt update -y
RUN apt upgrade -y
RUN apt install -y \
    apache2 \
    apache2-bin \
    apt-utils \
    apt-transport-https \
    arping \
    arptables \
    bind9 \
    bind9-utils \
    bison \
    bridge-utils \
    build-essential \
    curl \
    diffutils \
    dnsutils \
    dublin-traceroute  \
    ethtool \
    expect \
    flex \
    geoip-database \
    git \
    gnupg \
    hping3 \
    ieee-data \
    ifupdown \
    iperf3 \
    iptables \
    iputils-ping \
    iputils-tracepath \
    less \
    libdublintraceroute-dev \
    libjsoncpp-dev \
    libpcap-dev \
    libtins-dev \
    links \
    lsb-base \
    lsb-release \
    make \
    man-db \
    mtr \
    nano \
    ndisc6 \
    net-tools \
    netbase \
    netcat-openbsd \
    openssh-client \
    openssh-server \
    openssh-sftp-server \
    openssl \
    pkg-config \
    python3-dev \
    python3-pip \
    radvd \
    rsync \
    screen \
    sed \
    tar \
    tcpdump \
    telnet \
    tmux \
    traceroute \
    wget \
    vim
RUN apt clean

