/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    application
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.0.1")
    
    implementation("org.eclipse.basyx:basyx.sdk:1.4.0")
    implementation("org.eclipse.basyx:basyx.components.registry:1.4.0")
    implementation("org.eclipse.basyx:basyx.components.AASServer:1.4.0")

    implementation("com.jcraft:jsch:0.1.55")
    implementation("org.apache.httpcomponents:fluent-hc:4.5.14")
}

application {
    // Define the main class for the application.
    mainClass.set("ovs_aas.App")
}

tasks.withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar> {
    setZip64(true)
    manifest.attributes["Main-Class"] = application.mainClass
    archiveFileName.set("OVS_AAS.jar")
    destinationDirectory.set(file("/home/riccardo/Desktop/Kathara/KatharaAAS/aas_project"))
}
